title: Huu Thieu
author:
  name: Huu Thieu
  email: huuthieucqt@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
 Nơi chia sẻ kiến thức về công nghệ và những trải nghiệm cuộc sống của mình.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huuthieu.github.io" # the base hostname & protocol for your site
lang: vi-VN

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: classic

  # Customize the navigation header
  header_pages:
    - about.md
    - categories/programming.html
    - categories/life.html
    - categories/reading.html

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github: huuthieu
    # devto: jekyll
    # dribbble: jekyll
    facebook: huuthieu.teenhotboy
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: thieu-do-huu-001a67129
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Header pages are configured in the minima section above

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "post"
      
permalink: /:title 
